site_name: chen
site_description: 'A Material Design theme for MkDocs'
site_author: 'chen'
site_url: 'https://chenpenghuan.github.io'
copyright: 'Copyright © 2021'
nav:
- 工具: [git.md,mkdocs.md,macos.md,zsh.md]
- 开发: [k8s.md,java.md,springboot.md]
- 其他: [aws压缩图片.md]
- 关于: about.md
theme:
  name: 'material'
  custom_dir: 'themes/material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'Cyan'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo:
    icon: "\uE80C"
  feature:
    tabs: false
extra_javascript:
  - js/raphael.min.js
  - js/underscore-min.js
  - js/sequence-diagram-min.js
  - js/flowchart.min.js
  - js/umlconvert.js
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
- css/mermaid.min.css


